"""updated assessment table

Revision ID: 07c8d8b13f4d
Revises: 014c0ea16fad
Create Date: 2023-08-15 08:15:09.331404

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '07c8d8b13f4d'
down_revision = '014c0ea16fad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('is_marked', sa.Boolean(), server_default='FALSE', nullable=False))
    op.alter_column('assessments', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assessments', 'end_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('assessments', 'is_marked')
    # ### end Alembic commands ###
