"""updated questions

Revision ID: 10270719c168
Revises: 73e549a9e354
Create Date: 2023-06-20 20:57:49.379890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10270719c168'
down_revision = '73e549a9e354'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('answer_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'answer_type')
    # ### end Alembic commands ###
