"""updated questions 2

Revision ID: 3855dc41ff0d
Revises: 10270719c168
Create Date: 2023-06-20 21:33:27.560197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3855dc41ff0d'
down_revision = '10270719c168'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
