"""upgrade user data

Revision ID: 3ccc2d757e94
Revises: f56079a9eca2
Create Date: 2023-05-30 09:54:42.123415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ccc2d757e94'
down_revision = 'f56079a9eca2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instructors', sa.Column('faculty', sa.String(), nullable=False))
    op.add_column('instructors', sa.Column('department', sa.String(length=3), nullable=False))
    op.add_column('students', sa.Column('faculty', sa.String(), nullable=False))
    op.add_column('students', sa.Column('department', sa.String(length=3), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'department')
    op.drop_column('students', 'faculty')
    op.drop_column('instructors', 'department')
    op.drop_column('instructors', 'faculty')
    # ### end Alembic commands ###
