"""added is_accepted field to course instructors

Revision ID: 409050172c84
Revises: eb8a24647c7c
Create Date: 2023-03-16 10:43:16.415136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '409050172c84'
down_revision = 'eb8a24647c7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course instructors', sa.Column('is_accepted', sa.Boolean(), server_default='FALSE', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('course instructors', 'is_accepted')
    # ### end Alembic commands ###
