"""remove field from submit table

Revision ID: 53254d8446af
Revises: dc58283d7d5d
Create Date: 2023-03-16 15:58:28.553189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53254d8446af'
down_revision = 'dc58283d7d5d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'is_correct')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
