"""modified question table - spell change

Revision ID: 53743c096015
Revises: c80f915b1594
Create Date: 2023-03-16 12:54:52.237274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53743c096015'
down_revision = 'c80f915b1594'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('courses_description_key', 'courses', type_='unique')
    op.add_column('questions', sa.Column('is_multi_choice', sa.Boolean(), server_default='FALSE', nullable=False))
    op.drop_column('questions', 'is_multi_chioce')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('is_multi_chioce', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('questions', 'is_multi_choice')
    op.create_unique_constraint('courses_description_key', 'courses', ['description'])
    # ### end Alembic commands ###
