"""model updates

Revision ID: 56c42438a219
Revises: 4a6d7b3005ea
Create Date: 2023-08-07 16:29:25.606849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56c42438a219'
down_revision = '4a6d7b3005ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
