"""updated questions to include num answers

Revision ID: 99b41fc771be
Revises: 788f0905768b
Create Date: 2023-06-26 22:54:15.590597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99b41fc771be'
down_revision = '788f0905768b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
