"""Added creator_id columns to courses and assessments tables

Revision ID: a24a2d97a667
Revises: 07c8d8b13f4d
Create Date: 2023-09-09 10:24:52.649376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a24a2d97a667'
down_revision = '07c8d8b13f4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'assessments', 'instructors', ['creator_id'], ['id'], ondelete='NO ACTION')
    op.add_column('courses', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'courses', 'instructors', ['creator_id'], ['id'], ondelete='NO ACTION')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'creator_id')
    op.drop_constraint(None, 'assessments', type_='foreignkey')
    op.drop_column('assessments', 'creator_id')
    # ### end Alembic commands ###
