"""modified course on desc column

Revision ID: c80f915b1594
Revises: 0b3e229df80e
Create Date: 2023-03-16 12:47:55.160352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c80f915b1594'
down_revision = '0b3e229df80e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
