"""added field from submit table

Revision ID: ce3f372caaa6
Revises: 53254d8446af
Create Date: 2023-03-16 16:48:16.631614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce3f372caaa6'
down_revision = '53254d8446af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('stu_answer', sa.String(), nullable=False))
    op.add_column('submissions', sa.Column('ref_answer_id', sa.Integer(), nullable=False))
    op.drop_column('submissions', 'answer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('submissions', 'ref_answer_id')
    op.drop_column('submissions', 'stu_answer')
    # ### end Alembic commands ###
