"""added endtime to assessment

Revision ID: f56079a9eca2
Revises: 3a1f061ab77d
Create Date: 2023-03-22 08:20:01.647939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f56079a9eca2'
down_revision = '3a1f061ab77d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('end_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'end_date')
    # ### end Alembic commands ###
